spring:
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    drop-first: false
    enabled: true
    default-schema: public 
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    lazy-initialialization: true
  web:
    resources:
      static-locations: 
        - classpath:/static/
      cache:
        period: 0
  threads:
    virtual:
      enabled: true

server: ${SERVER_PORT}

